//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Scripts/InputController.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputController : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputController()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputController"",
    ""maps"": [
        {
            ""name"": ""Normal"",
            ""id"": ""0c491544-f2db-4106-b3e0-835a8a4e2d93"",
            ""actions"": [
                {
                    ""name"": ""mousePosition"",
                    ""type"": ""Value"",
                    ""id"": ""40a3f204-fda2-4e5e-b22d-ef45e5665836"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""mousePress"",
                    ""type"": ""Button"",
                    ""id"": ""c8951d67-0038-45b0-b7e4-456a8fbe6029"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Esc"",
                    ""type"": ""Button"",
                    ""id"": ""46fb4cb7-51c2-4d6e-8df7-71d425eb3764"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""spellCast1"",
                    ""type"": ""Button"",
                    ""id"": ""c18f9ec9-8bb1-4a99-ad7e-c0ede6770ca2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""spellCast2"",
                    ""type"": ""Button"",
                    ""id"": ""6c5088db-74ad-40f4-acb2-403d58de69c5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""spellCast3"",
                    ""type"": ""Button"",
                    ""id"": ""2ad8a0d9-e554-46d1-8eb5-0971d9513a6b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""spellCast4"",
                    ""type"": ""Button"",
                    ""id"": ""93f7a40d-d082-49f0-810c-05ceafc9c777"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dash"",
                    ""type"": ""Button"",
                    ""id"": ""7caa65bc-0b4e-4c09-93c0-70daf21766c1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CTRL"",
                    ""type"": ""Button"",
                    ""id"": ""16f9ee90-0c36-40d5-a10f-1cc520155d1b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""87a36830-8175-4379-a898-de8d6bd8fc61"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""mousePosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f5c9d78f-1654-4be0-a2c9-98e2cae194ee"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""mousePosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f7f6c8cf-6b51-44f1-85d7-db3198998a36"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""mousePress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""584fe0f9-8ef0-48f1-834a-d17b89e9b04c"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""mousePress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1ca67770-77d5-4ac7-9dde-0a968056b2b1"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Esc"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a30054e5-c2f7-4ad7-9bc4-25c9183042b2"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Esc"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c57bac9d-c6b9-491b-88cf-b741748e83d0"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""spellCast2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7aec7242-1a35-47d4-ad6f-1a289fd4c126"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""spellCast3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""57e9729a-8819-4441-8011-38405c3e9a31"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""spellCast4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4d8ca77c-d8e3-4546-b05d-d265493817b9"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""spellCast1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""663a38be-fcb8-43bd-bb7b-b31ef2fc41c5"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8c92406a-cab1-4777-aad0-0d6079653c5a"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CTRL"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d61b598a-552d-4e49-acb5-170799ccde58"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CTRL"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Normal
        m_Normal = asset.FindActionMap("Normal", throwIfNotFound: true);
        m_Normal_mousePosition = m_Normal.FindAction("mousePosition", throwIfNotFound: true);
        m_Normal_mousePress = m_Normal.FindAction("mousePress", throwIfNotFound: true);
        m_Normal_Esc = m_Normal.FindAction("Esc", throwIfNotFound: true);
        m_Normal_spellCast1 = m_Normal.FindAction("spellCast1", throwIfNotFound: true);
        m_Normal_spellCast2 = m_Normal.FindAction("spellCast2", throwIfNotFound: true);
        m_Normal_spellCast3 = m_Normal.FindAction("spellCast3", throwIfNotFound: true);
        m_Normal_spellCast4 = m_Normal.FindAction("spellCast4", throwIfNotFound: true);
        m_Normal_Dash = m_Normal.FindAction("Dash", throwIfNotFound: true);
        m_Normal_CTRL = m_Normal.FindAction("CTRL", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Normal
    private readonly InputActionMap m_Normal;
    private INormalActions m_NormalActionsCallbackInterface;
    private readonly InputAction m_Normal_mousePosition;
    private readonly InputAction m_Normal_mousePress;
    private readonly InputAction m_Normal_Esc;
    private readonly InputAction m_Normal_spellCast1;
    private readonly InputAction m_Normal_spellCast2;
    private readonly InputAction m_Normal_spellCast3;
    private readonly InputAction m_Normal_spellCast4;
    private readonly InputAction m_Normal_Dash;
    private readonly InputAction m_Normal_CTRL;
    public struct NormalActions
    {
        private @InputController m_Wrapper;
        public NormalActions(@InputController wrapper) { m_Wrapper = wrapper; }
        public InputAction @mousePosition => m_Wrapper.m_Normal_mousePosition;
        public InputAction @mousePress => m_Wrapper.m_Normal_mousePress;
        public InputAction @Esc => m_Wrapper.m_Normal_Esc;
        public InputAction @spellCast1 => m_Wrapper.m_Normal_spellCast1;
        public InputAction @spellCast2 => m_Wrapper.m_Normal_spellCast2;
        public InputAction @spellCast3 => m_Wrapper.m_Normal_spellCast3;
        public InputAction @spellCast4 => m_Wrapper.m_Normal_spellCast4;
        public InputAction @Dash => m_Wrapper.m_Normal_Dash;
        public InputAction @CTRL => m_Wrapper.m_Normal_CTRL;
        public InputActionMap Get() { return m_Wrapper.m_Normal; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(NormalActions set) { return set.Get(); }
        public void SetCallbacks(INormalActions instance)
        {
            if (m_Wrapper.m_NormalActionsCallbackInterface != null)
            {
                @mousePosition.started -= m_Wrapper.m_NormalActionsCallbackInterface.OnMousePosition;
                @mousePosition.performed -= m_Wrapper.m_NormalActionsCallbackInterface.OnMousePosition;
                @mousePosition.canceled -= m_Wrapper.m_NormalActionsCallbackInterface.OnMousePosition;
                @mousePress.started -= m_Wrapper.m_NormalActionsCallbackInterface.OnMousePress;
                @mousePress.performed -= m_Wrapper.m_NormalActionsCallbackInterface.OnMousePress;
                @mousePress.canceled -= m_Wrapper.m_NormalActionsCallbackInterface.OnMousePress;
                @Esc.started -= m_Wrapper.m_NormalActionsCallbackInterface.OnEsc;
                @Esc.performed -= m_Wrapper.m_NormalActionsCallbackInterface.OnEsc;
                @Esc.canceled -= m_Wrapper.m_NormalActionsCallbackInterface.OnEsc;
                @spellCast1.started -= m_Wrapper.m_NormalActionsCallbackInterface.OnSpellCast1;
                @spellCast1.performed -= m_Wrapper.m_NormalActionsCallbackInterface.OnSpellCast1;
                @spellCast1.canceled -= m_Wrapper.m_NormalActionsCallbackInterface.OnSpellCast1;
                @spellCast2.started -= m_Wrapper.m_NormalActionsCallbackInterface.OnSpellCast2;
                @spellCast2.performed -= m_Wrapper.m_NormalActionsCallbackInterface.OnSpellCast2;
                @spellCast2.canceled -= m_Wrapper.m_NormalActionsCallbackInterface.OnSpellCast2;
                @spellCast3.started -= m_Wrapper.m_NormalActionsCallbackInterface.OnSpellCast3;
                @spellCast3.performed -= m_Wrapper.m_NormalActionsCallbackInterface.OnSpellCast3;
                @spellCast3.canceled -= m_Wrapper.m_NormalActionsCallbackInterface.OnSpellCast3;
                @spellCast4.started -= m_Wrapper.m_NormalActionsCallbackInterface.OnSpellCast4;
                @spellCast4.performed -= m_Wrapper.m_NormalActionsCallbackInterface.OnSpellCast4;
                @spellCast4.canceled -= m_Wrapper.m_NormalActionsCallbackInterface.OnSpellCast4;
                @Dash.started -= m_Wrapper.m_NormalActionsCallbackInterface.OnDash;
                @Dash.performed -= m_Wrapper.m_NormalActionsCallbackInterface.OnDash;
                @Dash.canceled -= m_Wrapper.m_NormalActionsCallbackInterface.OnDash;
                @CTRL.started -= m_Wrapper.m_NormalActionsCallbackInterface.OnCTRL;
                @CTRL.performed -= m_Wrapper.m_NormalActionsCallbackInterface.OnCTRL;
                @CTRL.canceled -= m_Wrapper.m_NormalActionsCallbackInterface.OnCTRL;
            }
            m_Wrapper.m_NormalActionsCallbackInterface = instance;
            if (instance != null)
            {
                @mousePosition.started += instance.OnMousePosition;
                @mousePosition.performed += instance.OnMousePosition;
                @mousePosition.canceled += instance.OnMousePosition;
                @mousePress.started += instance.OnMousePress;
                @mousePress.performed += instance.OnMousePress;
                @mousePress.canceled += instance.OnMousePress;
                @Esc.started += instance.OnEsc;
                @Esc.performed += instance.OnEsc;
                @Esc.canceled += instance.OnEsc;
                @spellCast1.started += instance.OnSpellCast1;
                @spellCast1.performed += instance.OnSpellCast1;
                @spellCast1.canceled += instance.OnSpellCast1;
                @spellCast2.started += instance.OnSpellCast2;
                @spellCast2.performed += instance.OnSpellCast2;
                @spellCast2.canceled += instance.OnSpellCast2;
                @spellCast3.started += instance.OnSpellCast3;
                @spellCast3.performed += instance.OnSpellCast3;
                @spellCast3.canceled += instance.OnSpellCast3;
                @spellCast4.started += instance.OnSpellCast4;
                @spellCast4.performed += instance.OnSpellCast4;
                @spellCast4.canceled += instance.OnSpellCast4;
                @Dash.started += instance.OnDash;
                @Dash.performed += instance.OnDash;
                @Dash.canceled += instance.OnDash;
                @CTRL.started += instance.OnCTRL;
                @CTRL.performed += instance.OnCTRL;
                @CTRL.canceled += instance.OnCTRL;
            }
        }
    }
    public NormalActions @Normal => new NormalActions(this);
    public interface INormalActions
    {
        void OnMousePosition(InputAction.CallbackContext context);
        void OnMousePress(InputAction.CallbackContext context);
        void OnEsc(InputAction.CallbackContext context);
        void OnSpellCast1(InputAction.CallbackContext context);
        void OnSpellCast2(InputAction.CallbackContext context);
        void OnSpellCast3(InputAction.CallbackContext context);
        void OnSpellCast4(InputAction.CallbackContext context);
        void OnDash(InputAction.CallbackContext context);
        void OnCTRL(InputAction.CallbackContext context);
    }
}
